/**
 * Eduraa Mobile — Paper generation jobs API
 *
 * School papers are generated by a background worker that the backend allows up
 * to 30 minutes, so they are queued and polled rather than awaited on one
 * request.
 */

import apiClient from "./client";
import type { PaperGenerateRequest, QuestionVisualPayload } from "../types";

export type PaperGenerationStatus =
  | "idle"
  | "queued"
  | "preparing"
  | "generating"
  | "validating"
  | "saving"
  | "completed"
  | "failed"
  | "cancelled";

export interface PaperGenerationPreviewQuestion {
  slot_index: number;
  section_title: string | null;
  question_text: string;
  question_type: string;
  difficulty: string;
  marks: number;
  options?:
    | Array<{ id: string; text: string; is_correct?: boolean }>
    | Record<string, unknown>
    | null;
  answer_key?: string | Record<string, unknown> | null;
  subtopic_tags: string[];
  visual_payload?: QuestionVisualPayload | null;
}

export interface PaperGenerationJob {
  job_id: string;
  paper_id: string | null;
  status: PaperGenerationStatus;
  stage: string | null;
  progress: number | null;
  message: string | null;
  completed_units: number | null;
  total_units: number | null;
  preview_questions: PaperGenerationPreviewQuestion[];
  can_cancel: boolean;
  title: string | null;
  created_at: string | null;
  updated_at: string | null;
  completed_at: string | null;
  error_code: string | null;
  error_message: string | null;
}

const ACTIVE_STATUSES = new Set<PaperGenerationStatus>([
  "queued",
  "preparing",
  "generating",
  "validating",
  "saving",
]);

export function isPaperGenerationActive(status?: PaperGenerationStatus | null) {
  return Boolean(status && ACTIVE_STATUSES.has(status));
}

export const paperGenerationJobsApi = {
  create: async (
    payload: PaperGenerateRequest,
  ): Promise<PaperGenerationJob> => {
    const response = await apiClient.post<PaperGenerationJob>(
      "/papers/generation-jobs",
      payload,
    );
    return response.data;
  },

  getById: async (jobId: string): Promise<PaperGenerationJob> => {
    const response = await apiClient.get<PaperGenerationJob>(
      `/papers/generation-jobs/${jobId}`,
    );
    return response.data;
  },

  getActive: async (): Promise<PaperGenerationJob | null> => {
    const response = await apiClient.get<PaperGenerationJob | null>(
      "/papers/generation-jobs/active",
    );
    return response.data ?? null;
  },
};
